# state.py
# ─────────────────────────────────────────────────────
# The AgentState is the shared memory of the agent.
# Every node reads from it and writes back to it.
# Think of it as a baton passed between nodes —
# each node adds its result before passing it on.
# ─────────────────────────────────────────────────────
from typing import TypedDict, List, Optional, Any
from langgraph.graph.message import add_messages
from typing import Annotated

class AgentState(TypedDict):
    # The original question from the user
    question: str

    # Database schema discovered by inspect_schema node
    # Format: {table_name: {columns: [...], sample_rows: [...]}}
    schema: dict

    # Hints from dataset_config.yaml fed to the SQL generator
    hints: List[str]

    # The SQL query generated by Vertex AI
    sql: str

    # Raw rows returned from MySQL
    raw_data: List[dict]

    # Text analysis written by Vertex AI
    analysis: str

    # Base64 PNG chart from mcp_chart
    chart_base64: str

    # Chart metadata
    chart_type: str

    # Structured final output sent to the API
    json_output: dict

    # Last error message — used by retry logic
    error: str

    # How many times we've retried SQL generation
    retry_count: int

    # Conversation history for multi-turn support
    messages: Annotated[list, add_messages]